### ISSUE TITLE
Release 3.0.0-beta8 with ECL 3.2.0?

### ISSUE THREAD

**Issue by donquixote** [openeuropa/oe_theme#1025]
The latest beta7 release has ECL 3.1.2. This was released Dec 06, 2021. https://github.com/openeuropa/oe_theme/releases/tag/3.0.0-beta7

The -dev branch has ECL 3.2.0.

The themer in my team asked me if we can upgrade to ECL 3.2.0, because this would solve a few issues.

> We should upgrade ECL to v3.2.0 for a couple of things (remove the border under breadcrumb which is just a detail, avoid half of countries to be hidden which is not only a detail)

Is a new release planned soon?
I could patch the package.json, but I don't know which other work went into oe_theme to make it compatible with the new ECL 3.2.0.

**Comment by brummbar** [comment]
We made https://github.com/openeuropa/oe_theme/releases/tag/3.0.0-beta8 today with ECL 3.2.2.
