### ISSUE TITLE
Main menu dropdown doesn't work 

### ISSUE THREAD

**Issue by LOBsTerr** [openeuropa/oe_theme#114]
### Issue
When I to click on main menu items with arrows down nothing happens.
### How to reproduce
1) Fresh drupal site
2) Add theme and install it
3) install drush en oe_theme_demo
4) Open main page and try to click the menu items with sub levels
5) open admin/appearance/styleguide. It works there, but still looks strange, like menu doesn't have borders.

### Info
Version 0.5.1
Browser: Google Chrome

P.S. It works in Firefox

**Comment by LOBsTerr** [comment]
Installed the theme on my working machine it works there. I will check it

**Comment by brummbar** [comment]
Closing as old. Open a new issue if it's still not working properly.
