### ISSUE TITLE
Instead of image presentation displayed the input field

### ISSUE THREAD

**Issue by LOBsTerr** [openeuropa/oe_theme#34]
### How to reproduce
1) I have generated some content content type Article
2) when open the content instead of the image I see input field
3) In the view mode "Image" formatter is used

![screenshot from 2018-02-22 13-43-07](https://user-images.githubusercontent.com/537500/36539306-a9091498-17d6-11e8-9a9b-5fc6b92e4f55.png)

Expected behavior an image should be displayed

**Comment by ademarco** [comment]
@LOBsTerr this is now tracked on OPENEUROPA-345.

**Comment by imanoleguskiza** [comment]
Added a PR here: https://github.com/openeuropa/oe_theme/pull/44
