### ISSUE TITLE
Dropdown list missing icon

### ISSUE THREAD

**Issue by LOBsTerr** [openeuropa/oe_theme#35]
### Reproduce
1) Create a view displaying any  content items
2) Expose the filter and operators
3) Dropdown should have icon, but it doesn't

![screenshot from 2018-02-22 14-17-21](https://user-images.githubusercontent.com/537500/36540734-c2ca674c-17db-11e8-9851-85445e20d16a.png)

**Comment by ademarco** [comment]
Thank you for reporting, this is addressed in https://github.com/openeuropa/oe_theme/pull/36/commits/6cc08c262db3d1ec44ba0ae98911aa5f17d62527
