### ISSUE TITLE
Form inputs are implement ECL presentation

### ISSUE THREAD

**Issue by LOBsTerr** [openeuropa/oe_theme#37]
### How to reproduce
1) Install druhs en examples form_api_example -y
2) Open URL 

examples/form-api-example/input-demo

3) You will see that many elements look different

### Expected behaviour
All standard form items and widget should implement ECL styles.

**Comment by LOBsTerr** [comment]
I also recommend to check other examples, you will find other broken items.

**Comment by ademarco** [comment]
Using `form_api_example` sounds like a good idea, thank you for that! We could ditch the oe_theme_test module then, which is something we wanted to do anyway.

**Comment by drupol** [comment]
Very cool ! Like it :)

**Comment by LOBsTerr** [comment]
Actually, on one of Drupal meetups. There was a good idea to create a module, which will present all standard Drupal use cases on one page. So, we can check easily any theme for any kind of issues on one page. I tried to find something like. Unfortunately, it does't exist :(

**Comment by ademarco** [comment]
We now have the [Style guide module](https://www.drupal.org/project/styleguide) available as a development dependency and enabled when developing the theme. You can find a link to that page in the main menu. Closing the issue.
