### ISSUE TITLE
Status messages miss an icon

### ISSUE THREAD

**Issue by LOBsTerr** [openeuropa/oe_theme#38]
![screenshot from 2018-02-22 14-42-34](https://user-images.githubusercontent.com/537500/36541598-bd5fbaac-17de-11e8-92e7-66226f7f78a3.png)

The message block should have an icon like here: https://ec-europa.github.io/europa-component-library/components/preview/ecl-messages--info

**Comment by ademarco** [comment]
Thanks for reporting, this is addressed in https://github.com/openeuropa/oe_theme/pull/36/commits/6cc08c262db3d1ec44ba0ae98911aa5f17d62527
