### ISSUE TITLE
Select element template doesn't support container widths

### ISSUE THREAD

**Issue by kp77** [openeuropa/oe_theme#386]
The select template (`templates/form/select.html.twig`) currently doesn't support adding ECL classes for container width.

According to the ECL2 documentation the container width classes (`ecl-select__container--s`, `ecl-select__container--m`, `ecl-select__container--l`) should be added on the outer wrapper of the element.

At the moment it is not possible to add those classes without overriding the template:

https://github.com/openeuropa/oe_theme/blob/2.x/templates/form/select.html.twig#L14

**Comment by kp77** [comment]
Created a PR, with the template override I used in our project:

https://github.com/openeuropa/oe_theme/pull/392

**Comment by ademarco** [comment]
This has been merged and released on linked PR.
