### ISSUE TITLE
The module oe_theme_helper has conflicts with the module Drupal/redirect

### ISSUE THREAD

**Issue by milioce** [openeuropa/oe_theme#406]
**Description:**
If the module Drupal/redirect is enabled an error appears.

**Error**
The website encountered an unexpected error. Please try again later.
TypeError: Argument 6 passed to Drupal\oe_theme_helper\Loader\ComponentLibraryLoader::__construct() must be an instance of Drupal\Core\Logger\LoggerChannelFactory, instance of Drupal\redirect_404\Render\Redirect404LogSuppressor given, called in /.../web/core/lib/Drupal/Component/DependencyInjection/Container.php on line 289 in Drupal\oe_theme_helper\Loader\ComponentLibraryLoader->__construct() 
(line 37 of themes/contrib/oe_theme/modules/oe_theme_helper/src/Loader/ComponentLibraryLoader.php).

**Version**
2.x

**Suggested soluction**
Change LoggerChannelFactory to LoggerChannelFactoryInterface
in oe_theme/modules/oe_theme_helper/src/Loader/ComponentLibraryLoader.php

**Comment by brummbar** [comment]
Hello @milioce , thanks for the report! We will work on this now as priority.

**Comment by ademarco** [comment]
@milioce we have released 2.1.2 with a fix, please feel free to close this ticket if the new release solves the issue for you.
