### ISSUE TITLE
oe_theme CSS and JS libraries are not loaded when child theme is the active theme

### ISSUE THREAD

**Issue by pgrandeg** [openeuropa/oe_theme#409]
**Description:**
When you are using a child theme of oe_theme component, theme's JS and CSS files are not loaded.

**Error**
When a child theme of oe_theme is being used in openeuropa, following libraries are not being loaded:
dist/xx/styles/ecl-xx-preset-website.css
dist/xx/styles/ecl-xx-preset-legacy-website.css
css/style-ec.css
dist/xx/scripts/ecl-xx-preset-website.js
dist/xx/scripts/ecl-xx-preset-legacy-website.js
js/ecl_auto_init.js

The issue is on "oe_theme/modules/oe_theme_helper/oe_theme_helper.module:32" where the if is looking if the active theme is 'oe_theme' but no a child theme. It causes broken header and footer along the site.

**Version**
2.x

**Suggested soluction**
Add second condition using php array_key_exists('oe_theme', $active_theme->getBaseThemes())

**Comment by pgrandeg** [comment]
#410

**Comment by ademarco** [comment]
This has been fixed and merged, it will be included in the next release. Closing.
