### ISSUE TITLE
blockquote paragraph

### ISSUE THREAD

**Issue by kimlop** [openeuropa/oe_theme#415]
we starting to use oe_theme with oe_paragraphs module, and we added a node with one blockquote paragraph and this is the result on save: 

Drupal\Component\Plugin\Exception\PluginNotFoundException: The "blockquote" plugin does not exist. Valid plugin IDs for Drupal\ui_patterns\UiPatternsManager are: in Drupal\Core\Plugin\DefaultPluginManager->doGetDefinition() (line 53 of /var/www/html/build/core/lib/Drupal/Component/Plugin/Discovery/DiscoveryTrait.php).

In the components folder there is the relative component called: ec-component-blockquote

We are not sure why we obtain this error.

**Comment by ademarco** [comment]
That's an error coming form UI Patterns module, it means it did not find the blockquote pattern, which is there. Did you enable the oe_theme_helper module too as described [here](https://github.com/openeuropa/oe_theme#enable-the-theme)?

Also, when reporting always include which versions of the different components you are using and a full error stack, that would help us identifying the issue.

**Comment by kimlop** [comment]
yes, I followed the instructions.
I'm using the oe_paragraphs version 1.3.0 and its docker container, with the oe_theme version 2.1.2.
I'm also have render issues with display_suite and views that I didn't have with version 1.x of oe_theme

**Comment by ademarco** [comment]
Have you enabled the oe_theme_helper module too?

**Comment by kimlop** [comment]
yes

**Comment by kimlop** [comment]
I solved with the last dev version of oe_paragraphs
