### ISSUE TITLE
oe_theme v2.1.3 Language switcher doesn't work using subtheme

### ISSUE THREAD

**Issue by pgrandeg** [openeuropa/oe_theme#426]
Dear team,

We are experimening an issue while working on child theme of oe_theme 2.1.3.
The issue is because anchor data-ecl-language-selector is not getting proper click event of ecl-eu-preset-legacy-website.js.

Do you know any possible solution? Please, tell me if more information is needed.

Thank you in advance
Regards

**Comment by imanoleguskiza** [comment]
Hi @pgrandeg, behavior of the language switcher is largely defined by the ECL itself. As long as you follow the structure and initialize the js correctly it should work fine. You mention you are using a subtheme, did you do any customizations to the component perhaps?

**Comment by pgrandeg** [comment]
Ok @imanoleguskiza , thank you. The issue was an overriding twig in our subtheme. I'm sorry!
