### ISSUE TITLE
Responsive interface for a mobile – ECL1-1 and ECL-2

### ISSUE THREAD

**Issue by timpevi** [openeuropa/oe_theme#433]
We have a project ATI which requires a Responsive interface for a mobile.

We have been recommended by DEVOPS team to contact you on this point.

 

Context

We are developing a Drupal 8 application for which we have already a first iteration deployed on Acceptance @ DIGIT

We have been told by our GROW communication unit that our application is currently using ECL 1 which explains why on the Mobile the font size of the title looks too big etc…

(the search field should be hidden) ….

We have been advised to use ECL 2 for a much better look and feel of our application on a mobile.

 

After investigating it turns out that currently we are using  “OpenEuropa” and this one uses a Drupal theme based on ECL 1.

 ++ 

Question

Did we do something wrong with OpenEuropa that we are restricted to ECL 1?

If ECL 2 is not possible for the time being, is it expected in a near future that OpenEuropa uses a Drupal theme based on ECL 2 ?

Any advice on this?

**Comment by faircma** [comment]
Referring to the closed ticket FRONT-812 (Closed today) asking how to use ECL 2 via OpenEuropa.
Thanks the good advice, we could indeed proceed with this move to ECL-2. 

Unfortunately it is not completely working when our application uses ECL 2, 
For example main problems are e.g.
-->      Header
           •	Before (ECL 1): EC Logo is displayed
           •	After: (ECL 2) Logo not appears 
-->      Menu
           •	Before: Menu items with sub-items are correct and could be expanded 
                (Tools, Technologies, …)
           •	After: Menu sub items are not visible and menu not expandable
-->      Building blocks on Homepage
           •	Before: Last release with 9 Tools are correctly displayed
           •	After: Block are displayed but not at the correct place, …
Could it be possible that some of these issues result from our development - made initially with 
ECL 1 Standards - which are no more compatible with ECL 2?
We'll check this internally with our development team 
but please let us know if you have the answer at hand:
      -   Should it not be automatic to switch from ECL 1 to ECL 2? 
or  -   Should we re-adapt indeed all the theme to the ECL 2 standard?

Have a nice Week-end.
ATI Project manager.
Malcolm 
@timpevi @bellith @floraug

**Comment by ademarco** [comment]
Hello, which version of the theme you are using? To use ECL 2.x you have to use oe_theme 2.x.

**Comment by tvb1507** [comment]
Hello @ademarco 

We use oe_theme 1.x in our ATI Project https://github.com/ec-europa/grow-ati-reference/blob/master/composer.json#L67

We base our choice from the master branch of the module when we start development in October 2019.

Now we want indeed upgrade our base theme from oe_theme 1.x to 2.x as we understand and receive information that oe_theme 2.x is stable also. but when we try in our development environment we have some issues like explain in @faircma comment. 

What it means? is mean that we make something wrong with our templates, our sub-themes? is mean that our templates are only compatible with oe_theme / ECL 1.x?
Have you any additional information how to upgrade oe_theme and sub-theme already working? 

If you want I can send you some screenshots of what I see when I upgrade oe_theme.

Thanks in advance for our support?

Regards,

Thibaut
CC @faircma @vintimpe @floraug

**Comment by ademarco** [comment]
@tvb1507 have you ran `drush updb` after updating to theme 2.x codebase?

**Comment by tvb1507** [comment]
Hello @ademarco 

Yes, after execute `drush updb` remarks in our comment appears

The most strange concern Header and Menu, we don't use special Templates for it.
Concerning " Building blocks on Homepage ", perhaps our template can be improved, but use ECL-1 standards.

Thanks,

Regards,

**Comment by ademarco** [comment]
If you have a sub-theme then, yes, things might be broken there. For example the ecl twig template loading has changed and, when using a sub-theme, you need to change that manually. Also try to Visit your sub-teme settings page, choose which Europa component library you need and re-submit it, this might help with setting the library.

**Comment by faircma** [comment]
Thanks for the information. I passed it to our developer who is back.
Have a nice evening.

**Comment by floraug** [comment]
Hello @ademarco,

I followed the steps to upgrade from ECL1 to ECL2:
```
- docker-compose exec web composer require openeuropa/ecl-twig-loader openeuropa/oe_theme
- docker-compose exec web composer ./vendor/bin/drush updatedb
- docker-compose exec web composer ./vendor/bin/drush cr (twice as first time it some errors)
```

To me is looking like the theme is not working even if I switched from our sub-theme to oe_theme, rebuild theme registry: [https://drive.google.com/file/d/19U2WHfyXojbzniC3j6cjrLQHJgS0OM0m/view?usp=sharing](https://drive.google.com/file/d/19U2WHfyXojbzniC3j6cjrLQHJgS0OM0m/view?usp=sharing)
![Uploading ecl2-second-image.png…]()

I was expecting to see something like the header and footer banners, main menu but it seems everything is plain (except css from our sub-theme - those images).

Before upgrading the site was looking like this:
![screencapture-grow-ati-acc-fpfis-tech-ec-europa-eu-2020-04-03-09_58_55](https://user-images.githubusercontent.com/23116463/78338638-68f8ce80-7593-11ea-835e-da16736b36e6.png)



Am I missing something? Any advice? 
Thank you

**Comment by brummbar** [comment]
@floraug , as written by @ademarco in the previous reply, did you go to the theme settings page, chose a component library and hit save?
In your case, since you have a sub-theme, make sure to go to the sub-theme settings page.

![image](https://user-images.githubusercontent.com/8488617/78531914-a99c5600-77e6-11ea-95c4-e78cebcb87db.png)

After pressing "Save configuration" (press it in any case, even if it seems an option is already selected), clear the caches just to be sure and visit the frontend.

**Comment by floraug** [comment]
Hello @brummbar, I wen to admin/appearance/settings/my_subtheme a couple of times and checked and unchecked various options and then saving the changes. I had EC value selected as component library all the time. But still it would not load the resources from oe_theme.

![image](https://user-images.githubusercontent.com/23116463/78552064-1cb5c480-7807-11ea-90b3-b80473b19381.png)

I upgraded to 2.2 and it seems that is it working, I didn't mentioned which version of oe_theme and it upgraded to 2.2 and seems like it is working now.

I still have the issue with missing EC logo:
![image](https://user-images.githubusercontent.com/23116463/78552359-a8c7ec00-7807-11ea-97bb-ea06335869f6.png)
It is loading templates from oe_theme block--system-branding-block.html.twig

**Comment by brummbar** [comment]
The only similar issue we had regarding styles was fixed back in 2.1.3 (#413).
I assumed you already tried with that version, since it was released on 5th of February and this issue was opened on the 21th.
Which version were you using before? So it can help others in the future.

Regarding your logo, I cannot help more, you need to look which path is being used for it. If you find an issue with oe_theme, feel free to post an issue with patch.
Also please note that the latest oe_theme version is 2.3.0.

**Comment by floraug** [comment]
We upgraded now from v1.7 to 2.2 (as 2.3 would throw errors), we didn't went through 2.1.3.

Well is using oe_theme/templates/blocks/block--system-branding-block.html.twi which references:
`<img
      alt="{{ site_logo_alt }}"
      title="{{ site_name }}"
      class="ecl-site-header__logo-image"
      src="{{ ecl_logo_path ~ '/logo--' ~ current_language_id|to_internal_language_id ~ '.svg'}}"
    />`

And is trying to load it from:
`/themes/contrib/oe_theme/dist//images/logo/logo--en.svg 404 (Not Found)`

Also I have another missing image:
`/themes/contrib/oe_theme/dist//images/icons/sprites/icons.svg net::ERR_ABORTED 404 (Not Found)`

**Comment by brummbar** [comment]
@floraug what I meant was to which version you tried to update when you posted [this comment](https://github.com/openeuropa/oe_theme/issues/433#issuecomment-608294640).
Anyway, glad that version 2.2 worked.

Regarding your logo issue, a correct path to the logo would be `"/themes/contrib/oe_theme/dist/ec/images/logo/logo--en.svg"`.
As you can see, you are still missing the component library, which should be there after saving the settings form as written above.

**Comment by floraug** [comment]
I was trying to update from 1.7 to 2.3 when I was having the errors.

Now I saved it again, (European Commission was selected already) and the missing 2 images are working.

![image](https://user-images.githubusercontent.com/23116463/78574349-2d2b6680-782a-11ea-8ba4-16f7ae894746.png)

I will give it a try to upgrade it to 2.3 now that everything is working.

Thank you @brummbar!

**Comment by brummbar** [comment]
@floraug any update? Did you manage to upgrade to the latest version?

**Comment by floraug** [comment]
Hello @brummbar As per my last comment:
_Now I saved it again, (European Commission was selected already) and **the missing 2 images are working**._

I went from 1.7 to 2.2 initially and then updated from 2.2 to 2.3 and it worked this way.

Thanks a lot for your help.

**Comment by brummbar** [comment]
Yep just wanted to be sure that you were able also to move to the later versions of oe_theme after the library thing was working. Perfect, I'll close this issue!
