### ISSUE TITLE
Is oe_content module now obligatory to use along with oe_theme module?

### ISSUE THREAD

**Issue by ansergeyg** [openeuropa/oe_theme#631]
Hi guys,
I see that you added now sub modules for theming content types coming from oe_content module.
I wonder what was the intention?
We want to use oe_theme module but don't want to use oe_content module. Now the oe_theme module just brings the whole shebang of modules that can only be used if oe_content is used. This solution looks odd to me.

Regards, Sergey

**Comment by ademarco** [comment]
The answer to your question is, and always will be: no.

You can use the theme without using oe_content, those optional sub-modules are to be enabled only if:

1. you are using oe_content, and
2. you want the content types of oe_content to be styled in a default way
