### ISSUE TITLE
Exception in eclFooterLinks

### ISSUE THREAD

**Issue by ansergeyg** [openeuropa/oe_theme#679]
Hi there, 

When using digit ec-europa toolkit and upgrading from 2.10.x version to 2.12.x version
there is an error on the website.

Got error 'PHP message: TypeError: Argument 2 passed to Drupal\\oe_theme_helper\\TwigExtension\\TwigExtension::eclFooterLinks() must be of the type array, null given, called in web/sites/default/files/php/twig/5fce3f1599faf_oe-corporate-blocks-ec-fo_Y4kmMlqGJnOQpBj1PaPcyXV-g/QjBPJ8JJBX8TFcWB544JmYdLcYBn-KRszeIWR84wGBI.php on line 39

Strange, maybe there is something else that needs to be configured?

But this is a straightforward reproducible bug if you rebuild and open any page (I mean not behat testing, but actual manual testing).

Regards, Sergey

**Comment by ademarco** [comment]
@ansergeyg theme from 2.12 is indeed not compatible with oe_corporate_blocks 2.x anymore, sorry about that, we should have added it in composer.json's conflict section. We will roll out a patch release for that.

**Comment by ansergeyg** [comment]
@ademarco , thank you for the clarification

Regards, Sergey

**Comment by ademarco** [comment]
In your project you can require the version below and it should work.
```
         "openeuropa/oe_corporate_blocks": "~3.0.0-beta3",
```

**Comment by ademarco** [comment]
@ansergeyg  PR opened, this will be fixed in our upcoming release 2.12.2.

**Comment by ademarco** [comment]
New release done, closing.
